/**
 * @neko/agent - Agent Application Package
 *
 * This package provides the agent runtime for AI-powered task execution.
 * It can run standalone (without platform) or integrated with platform.
 *
 * Standalone mode:
 * - Uses built-in LLM client
 * - Full MCP support
 * - Skill system
 *
 * Integrated mode:
 * - Uses platform's LLM routing
 * - Media generation via platform
 * - Workflow execution via platform
 */

// Re-export shared types for convenience
export type {
  // Agent types
  AgentState,
  AgentConfig,
  AgentContext,
  AgentStep,
  AgentResult,
  AgentCheckpoint,
  IAgentRuntime,
  // Hook types
  ExecutorHooks,
  ToolCallInfo,
  ToolResultWithMeta,
  ThinkContext,
  // MCP types
  IMCPManager,
  IMCPClient,
  MCPServerConfig,
  MCPToolDefinition,
  MCPToolResult,
  MCPResource,
  MCPPrompt,
  // Tool types
  IToolRegistry,
  Tool,
  ToolResult,
  ToolCategory,
  ToolCallRequest,
  // Platform types (for integration)
  IPlatform,
  IService,
  ChatMessage,
  ServiceResponse,
  StreamChunk,
  ServiceOptions,
  ToolDefinition,
  LLMProviderConfig,
} from '@neko/shared';

export {
  parseProviderCardMarkdown,
  ProviderCardRegistry,
  createProviderCardRegistry,
  ProviderRouter,
  createProviderRouter,
  loadProviderCardDirectory,
  registerProviderCardDirectory,
  registerRuntimeProviderCardDirectories,
  type ParseProviderCardOptions,
  type LoadProviderCardDirectoryOptions,
  type RegisterProviderCardDirectoryOptions,
  type ProviderCardLoaderFs,
  type ProviderCardDirent,
  type ProviderCardLoadError,
  type ProviderCardRuntimeLogger,
  type RegisterRuntimeProviderCardDirectoriesOptions,
  type RuntimeProviderCardDirectoryRegistrationResult,
  createProviderExpressionPromptFragments,
  type ProviderExpressionContextOptions,
} from './provider';

export {
  AgentProfileRegistry,
  ArtifactProfileRegistry,
  ProviderExpressionProfileRegistry,
  createArtifactProfileRegistry,
  createProviderExpressionProfileRegistry,
  BUILTIN_ARTIFACT_PROFILES,
  type AgentProfileDescriptor,
  type AgentProfileRegistryOptions,
} from './profile';

export {
  PERCEPTION_AUDIO_TRANSCRIBE_METADATA,
  PERCEPTION_IMAGE_SIMILARITY_METADATA,
  PERCEPTION_IMAGE_CLASSIFY_METADATA,
  PERCEPTION_DESCRIBE_INPUT_METADATA,
  PERCEPTION_VIDEO_DETECT_SHOTS_METADATA,
  PerceptionAudioTranscribeTool,
  PerceptionImageSimilarityTool,
  PerceptionImageClassifyTool,
  PerceptionDescribeInputTool,
  PerceptionVideoDetectShotsTool,
  createPerceptionTools,
  perceptionToolGroup,
  type PerceptionAudioTranscribeToolConfig,
  type PerceptionImageSimilarityToolConfig,
  type PerceptionImageClassifyToolConfig,
  type PerceptionToolMetadata,
  type PerceptionToolResult,
  type PerceptionClassifyClient,
  type PerceptionDetectShotsClient,
  type PerceptionSimilarityClient,
  type PerceptionTranscribeClient,
  BuiltinTool,
  createTool,
  ToolRegistry,
  createToolRegistry,
  ToolCategoryRegistry,
  createToolCategoryRegistry,
  // Core file/system tools
  ReadTool,
  WriteTool,
  BashTool,
  type BashToolOptions,
  ListDirectoryTool,
  GrepTool,
  type GrepToolOptions,
  MemoryWriteTool,
  createCoreTools,
  type CoreToolsOptions,
  // Injection constants
  DEFAULT_INJECTION_CONFIG,
  CORE_TOOLS,
} from './tools';

// Export logger
export { setRootLogger, getLogger as getAgentLogger } from './utils/logger';

// Export errors
export { AgentError, type AgentErrorCategory, type AgentErrorInfo } from './errors';

// Export executor

// Export memory
export { FileProjectMemoryManager, createFileProjectMemoryManager, MemoryRecall } from './memory';
export type { MemoryRecallOptions, RecalledMemory } from './memory';

// Export MCP
export {
  StdioMCPClient,
  HttpMCPClient,
  createMCPClient,
  MCPManager,
  MCPTool,
  connectMCPServersRuntime,
  createMcpToolCreationOptionsForExternalResearch,
  createMCPTools,
  createAllMCPTools,
  MCPTestService,
  getMCPTestService,
  type MCPToolCallManager,
  type MCPToolDiscoveryManager,
  type MCPRuntimeBootstrapLogger,
  type MCPRuntimeBootstrapOptions,
  type MCPRuntimeBootstrapResult,
  type MCPRuntimeConnectionFailure,
  type MCPRuntimeManager,
  type MCPRuntimeToolRegistry,
  type MCPTestConfig,
  type MCPTestResult,
} from './mcp';

// Export validation
export {
  // Types
  type ImageConstraints,
  type OutputConstraints,
  type ValidationHooksOptions,
  type ValidationError,
  type ValidationWarning,
  type ValidationResult,
  type ValidationErrorType,
  type ImageInfo,
  type MermaidValidationResult,
  type MermaidBlockInfo,
  type MermaidBlockValidationResult,
  type JsonBlockInfo,
  type JsonBlockValidationResult,
  type ValidationResultWithBlocks,
  // Constants
  DEFAULT_IMAGE_CONSTRAINTS,
  DEFAULT_OUTPUT_CONSTRAINTS,
  // Image Validator
  ImageValidator,
  ImageValidationError,
  createImageValidator,
  // Output Validator
  OutputValidator,
  createOutputValidator,
  // Validation Hooks
  ValidationHooks,
  createValidationHooks,
  // Extractors
  MermaidExtractor,
  JsonExtractor,
  createMermaidExtractor,
  createJsonExtractor,
  // Validators
  MermaidValidator,
  JsonSchemaValidator,
  LengthValidator,
  createMermaidValidator,
  createJsonSchemaValidator,
  createLengthValidator,
  // Checkers
  MermaidBlockChecker,
  createMermaidBlockChecker,
} from './validation';

// Export permission
export {
  // Types
  type PermissionMode,
  type PermissionDecision,
  type PermissionRules,
  type PermissionConfig,
  type PermissionCheckResult,
  type ToolConfirmationRequest,
  type ToolConfirmationResponse,
  type ConfirmToolCallback,
  type PermissionHooksOptions,
  // Constants
  DEFAULT_READ_ONLY_TOOLS,
  READ_ONLY_MCP_PREFIXES,
  DEFAULT_PERMISSION_CONFIG,
  PLAN_MODE_SYSTEM_REMINDER,
  // Rule Matcher
  PermissionRuleMatcher,
  createPermissionRuleMatcher,
  normalizeToolCall,
  matchesPattern,
  isInPatternList,
  isReadOnlyTool,
  isPlanMarkdownWrite,
  // Permission Hooks
  PermissionHooks,
  createPermissionHooks,
  ToolTraitsRegistry,
  DEFAULT_CREATIVE_TOOL_TRAITS,
} from './permission';

// Export prompt file projection
export {
  DEFAULT_AGENTS_FILE_CONTENT,
  DEFAULT_NEW_PROMPT_NAME,
  PROMPT_FILE_EXTENSION,
  buildAgentsFileLoadPlan,
  buildAgentsFilePlan,
  buildPromptConfigFilePlan,
  buildPromptFileContent,
  createPromptFileRuntime,
  ensurePromptFileExtension,
  extractPromptNameFromContent,
  generatePromptFileId,
  generatePromptFileName,
  projectPromptFileInfo,
  promptFileInfoToConfig,
  shouldScanPromptFile,
  syncPromptFilesWithConfig,
  type AgentsFileLoadCandidate,
  type PromptFileInfo,
  type PromptFileScanResult,
  type PromptFileScanResult as AgentPromptFileScanResult,
  type AgentsFileFailurePlan,
  type AgentsFilePlan,
  type LoadedAgentsFile,
  type PromptFileRuntime,
  type PromptFileRuntimeFs,
  type PromptFileRuntimeLogger,
  type PromptFileRuntimeOptions,
  type PromptFileRuntimePath,
  type PromptFileRuntimeStatLike,
  type PromptFileSaveResult,
  type PromptConfigFilePlan,
  type SavePromptFileInput,
  PromptManager,
  createPromptManager,
  // System Prompt Builder
  SystemPromptBuilder,
  createSystemPromptBuilder,
  runSystemPromptAgentsFileLoadRuntime,
  getDefaultPersonalPath,
  hasAgentsFile,
  BUILTIN_PROMPTS,
  BUILTIN_DEFAULT_PROMPT_EN,
  BUILTIN_DEFAULT_PROMPT_ZH,
  BUILTIN_PLAN_PROMPT_EN,
  BUILTIN_PLAN_PROMPT_ZH,
  type ISystemPromptBuilder,
  type SystemPromptBuilderConfig,
  type SystemPromptAgentsFileRuntimeDeps,
  type SystemPromptAgentsFileRuntimeInput,
  type PromptExecutionMode,
  type PromptLocale,
  type AgentsSource,
  type AgentsLoadResult,
  type BuiltinPromptKey,
  type PromptCompositionFragmentProjection,
  // Re-exported types from shared
  type Prompt,
  type PromptVariable,
  type PromptCategory,
  type RenderedPrompt,
  type IPromptManager,
} from './prompt';

// Export settings hook execution
export {
  type HookExecutionResult,
  type ISettingsFileSystem,
  type IShellExecutor,
  type LoadedSettingsHook,
  type SettingsHookLoadResult,
  type SettingsHookLoaderOptions,
  SettingsHookLoader,
  createSettingsHookLoader,
} from './hook-loader';

// Export session management
export {
  RetiredAgentMetadataStoreError,
  type RetiredAgentMetadataStoreKind,
} from './retired-metadata-store';
export {
  buildConversationHistoryClearedMessage,
  createConversationId,
  getConversationWorkDirHash,
  isCanonicalConversationId,
  parseConversationId,
  runCancelMessageRuntime,
  runClearAllConversationsRuntime,
  runClearHistoryRuntime,
  runConfirmToolRuntime,
  runDeleteConversationRuntime,
  runNewConversationRuntime,
  runSwitchConversationRuntime,
  type ConfirmToolRuntimeInput,
  type ConversationControlAction,
  type ConversationControlConversationInput,
  type ConversationControlDisposable,
  type ConversationControlRuntimeEffects,
  type ConversationControlRuntimeMessage,
  type ConversationControlRuntimeResult,
  type ConversationControlRuntimeWarning,
  type ConversationControlRuntimeWarningCode,
  type DeleteConversationRuntimeInput,
  type DeleteConversationRuntimeOptions,
  type ConversationIdOptions,
  type ParsedConversationId,
  type AgentEvent,
  type AgentEventType,
  type ExecutionMode,
  type CompressionResult,
  // Re-exported from permission
  type ToolConfirmationRequest as SessionToolConfirmationRequest,
  // Re-exported from validation
  type ValidationError as SessionValidationError,
  type ValidationWarning as SessionValidationWarning,
} from './session';

// Export task management
export {
  TaskManager,
  MemoryTaskStorage,
  SqliteTaskRecoveryStorage,
  SqliteTaskStorage,
  MemoryTaskRecoveryStorage,
  CLEANUP_TASK_STATUSES,
  DEFAULT_TASK_CLEANUP_INTERVAL_MS,
  DEFAULT_TASK_RETENTION_PERIOD_MS,
  RECOVERABLE_TASK_STATUSES,
  buildTaskStorageCleanupPlan,
  buildAgentTaskHostPrivateLeaseDiagnostic,
  createAgentTaskHostPrivateLease,
  AgentTaskResultObservationError,
  DEFAULT_AGENT_TASK_RESULT_DELIVERY_POLICY,
  createAgentTaskResultEvidenceId,
  createAgentTaskResultFollowUpRequestId,
  createAgentTaskResultObservationId,
  createAgentTaskResultObservationRecords,
  evaluateAgentTaskResultDelivery,
  filterRecoverableTasks,
  getAgentTaskResultDeliveryPolicy,
  isRecoverableTask,
  isRecoverableTaskStatus,
  isAgentTaskResultTerminalStatus,
  isTaskCleanupCandidate,
  isTaskCleanupStatus,
  normalizeAgentTaskResultDeliveryPolicy,
  normalizeAgentChildRunResultObservation,
  normalizeAgentTaskResultObservation,
  normalizeAgentTaskResultRefs,
  type TaskManagerOptions,
  type TaskRunLease,
  type TaskTerminalEvent,
  type TaskTerminalCallback,
  type TaskTerminalSubscriptionOptions,
  type ConcurrencyConfig,
  type IRuntimeTaskManager,
  type SqliteTaskStorageOptions,
  type TaskStorageCleanupPlan,
  type AgentTaskResultDeliveryDecision,
  type AgentTaskResultObservationDiagnosticCode,
  type AgentTaskResultObservationRecords,
  type NormalizeAgentChildRunResultObservationInput,
  type NormalizeAgentTaskResultObservationInput,
  buildCancelTaskActionPlan,
  buildClearCompletedTaskPlan,
  buildBackgroundTaskFailureUpdateView,
  buildRemoveTaskActionPlan,
  buildRetryTaskActionPlan,
  buildTaskResultOpenPlan,
  buildViewTaskResultActionPlan,
  createBackgroundTaskViewFromToolResultData,
  filterTasksForConversation,
  getTaskConversationId,
  getTaskResultUrl,
  matchesTaskConversation,
  mergeBackgroundTaskProgressView,
  runCancelTaskRuntime,
  runClearCompletedTasksRuntime,
  runRemoveTaskRuntime,
  runRetryTaskRuntime,
  runSendTasksRuntime,
  runViewTaskResultRuntime,
  toBackgroundTaskView,
  toBackgroundTaskViewStatus,
  toBackgroundTaskViewType,
  type CancelTaskActionPlan,
  type ClearCompletedTaskPlan,
  type RemoveTaskPlan,
  type RetryTaskPlan,
  type ConversationTasksRuntimeInput,
  type TaskActionRejectPlan,
  type TaskActionNoopPlan,
  type TaskActionRejectReason,
  type TaskMediaCandidate,
  type TaskRuntimeAction,
  type TaskRuntimeDeps,
  type TaskRuntimeEffects,
  type TaskRuntimeInput,
  type TaskRuntimeHostPrivateLeaseGuard,
  type TaskRuntimeMediaGateway,
  type TaskRuntimeMessage,
  type TaskRuntimeResult,
  type TaskRuntimeTaskManager,
  type TaskResultOpenPlan,
  type ViewTaskResultPlan,
  // Re-exported types from shared
  type Task,
  type TaskType,
  type TaskStatus,
  type TaskInput,
  type TaskOutput,
  type TaskProgressCallback,
  type ITaskManager,
  type ITaskStorage,
  type ITaskRecoveryStorage,
  type TaskRecoveryInfo,
  type SerializableTask,
  type TaskExecutor,
  type TaskExecutionContext,
  type TaskLifecycleMetadata,
  type AgentTaskResultDeliveryPolicy,
  type AgentTaskResultFollowUpRequest,
  type AgentTaskResultObservation,
  type AgentTaskResultRef,
  type AgentTaskResultRefKind,
  type AgentTaskResultSource,
  type AgentTaskResultTerminalStatus,
  type TaskCostPhase,
  type TaskInterruptPolicy,
  type TaskRecoverPolicy,
  type TaskRunMode,
  type BackgroundTaskView,
  type BackgroundTaskProgressPatch,
  type BackgroundTaskFailureUpdateOptions,
  type BackgroundTaskToolResultProjectionOptions,
  type BackgroundTaskViewStatus,
  type BackgroundTaskViewType,
  type AgentTaskHostPrivateLease,
  type AgentTaskHostSurface,
  type AgentTaskLeaseControl,
  type AgentTaskLeaseDiagnostic,
} from './task';

// Export commands (builtin slash commands)
export {
  // Types
  type BuiltinCommandName,
  type BuiltinCommand,
  type CommandCategory,
  type CommandContext,
  type CommandResult,
  type CommandAction,
  type CommandHandler,
  type CommandHandlerRegistration,
  type SlashCommandSurface,
  type SlashCommandSkillLike,
  type SlashCommandCatalogEntry,
  type BuildExtensionCommandHostEffectPlanInput,
  type BuildExtensionCommandResultPayloadInput,
  type ExtensionCommandHostEffect,
  type ExtensionCommandHostEffectPlan,
  type ExtensionCommandConversationSummary,
  type ExtensionCommandConversationSummarySource,
  type ExtensionCommandResultPayload,
  type ExtensionSlashCommandContextManager,
  type ExtensionSlashCommandConversationSource,
  type ExtensionSlashCommandRuntimeDeps,
  type ExtensionSlashCommandRuntimeEffects,
  type ExtensionSlashCommandRuntimeInput,
  type ExtensionSlashCommandRuntimeResult,
  type ExtensionSlashCommandSettingsSource,
  // Constants
  COMMAND_ALIASES,
  BUILTIN_COMMANDS,
  // Functions
  buildExtensionCommandConversationSummaries,
  buildExtensionCommandHostEffectPlan,
  buildExtensionCommandResultPayload,
  buildExtensionSlashStatusPayload,
  runExtensionSlashCommandRuntime,
  resolveCommandName,
  normalizeSlashCommandName,
  parseBuiltinCommandArgs,
  listSlashCommandCatalog,
  resolveSlashCommandCatalogEntry,
  getCliCommands,
  getExtensionCommands,
  getBuiltinCommand,
  isBuiltinCommand,
  getAllCommandNames,
  // Handlers
  handleHelp,
  handleStatus,
  handleClear,
  handleExit,
  handleConfig,
  handleModel,
  handleSettings,
  handlePermissions,
  handleInit,
  handleNew,
  handleResume,
  handleCompact,
  handlePlan,
  handleSkills,
  handleCommands,
  handleTools,
  handleTasks,
  handleMcp,
  buildAgentTerminalHelpSemantic,
  executeAgentTerminalSkillsSemantic,
  executeAgentTerminalCommandsSemantic,
  executeAgentTerminalToolsSemantic,
  type AgentTerminalSkillRow,
  type AgentTerminalToolRow,
  type AgentTerminalHelpSemanticResult,
  type AgentTerminalSkillsSemanticResult,
  type AgentTerminalCommandsSemanticResult,
  type AgentTerminalToolsSemanticResult,
  type AgentTerminalResourceCommandSemanticResult,
  type AgentCommandSessionSemanticResult,
  type AgentCommandConfigSnapshot,
  type AgentCommandConfigSemanticResult,
  type AgentCommandCoreSemanticResult,
  type AgentCommandShellSemanticResult,
  type AgentCommandSemanticResult,
  isAgentCommandSemanticFailure,
  // Utilities
  generateExtensionStatusData,
  // Executor
  parseSlashCommand,
  isSlashCommand,
  executeBuiltinCommand,
  executeSlashCommand,
  getCommandHandler,
} from './commands';

// Export input processing
export {
  InputProcessor,
  createInputProcessor,
  NodeFileReader,
  createNodeFileReader,
  DEFAULT_MENTION_EXCLUDED_DIRECTORIES,
  DEFAULT_MENTION_EXCLUDE_GLOB,
  isMentionExcludedPath,
  createWorkspaceFileIgnoreRules,
  matchesGitignoreRules,
  normalizeRelativePath,
  parseGitignoreRules,
  shouldIgnoreWorkspaceFile,
  VSCodeFileReader,
  createVSCodeFileReader,
  type VSCodeWorkspaceAPI,
  type WorkspaceFileIgnoreDecision,
  type WorkspaceFileIgnoreReason,
  type WorkspaceFileIgnoreRules,
  type FileReference,
  type ProcessedInput,
  type InputProcessorOptions,
  type IFileReader,
  type IInputProcessor,
} from './input';

// Export workspace/content layout helpers
export {
  NEKO_AGENTS_FILE_NAME,
  NEKO_CONTENT_DIR,
  NEKO_CONTENT_SUBDIRS,
  resolveAgentsFile,
  resolveNekoContentDir,
  resolvePersonalAgentsFile,
  resolvePersonalNekoContentDir,
  resolveProjectAgentsFile,
  resolveProjectNekoContentDir,
  type NekoContentSource,
  type NekoContentSubdir,
} from './workspace';

export {
  PersistedChildRunOwnershipError,
  requirePersistedSubAgentRunScope,
  requirePersistedTaskRunScope,
  type PersistedChildRunOwnershipDiagnostic,
  type PersistedChildRunOwnershipFailure,
  type PersistedChildRunRecordKind,
} from './runtime/persisted-child-run-ownership';
