export type CodiconName =
  | 'add'
  | 'check'
  | 'circle-large-filled'
  | 'circle-large-outline'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-up'
  | 'close'
  | 'copy'
  | 'cursor'
  | 'device-camera'
  | 'cloud-download'
  | 'edit'
  | 'file-media'
  | 'file-text'
  | 'gear'
  | 'account'
  | 'eye'
  | 'eye-closed'
  | 'inbox'
  | 'inspect'
  | 'loading'
  | 'lightbulb'
  | 'layout'
  | 'layout-centered'
  | 'layout-panel'
  | 'layout-sidebar-left'
  | 'layout-sidebar-right'
  | 'package'
  | 'lock'
  | 'move'
  | 'music'
  | 'play'
  | 'person'
  | 'refresh'
  | 'search'
  | 'settings'
  | 'screen-normal'
  | 'save'
  | 'symbol-misc'
  | 'symbol-ruler'
  | 'symbol-namespace'
  | 'symbol-color'
  | 'symbol-structure'
  | 'sync'
  | 'table'
  | 'trash'
  | 'type-hierarchy'
  | 'unlock';

export function toCodiconClassName(name: CodiconName): string {
  return `codicon codicon-${name}`;
}
